// GENERATED by scripts/build-logo.mjs — do not edit by hand.
// Filenames are content-hashed so a replaced logo is never served from cache.
export const logoAssets = {
  full: {
    onLight: "/images/logo-full.c79eecc0.png",
    onDark: "/images/logo-full-light.c79eecc0.png",
    width: 700,
    height: 502,
  },
  mark: {
    src: "/images/logo-mark.c79eecc0.png",
    width: 400,
    height: 360,
  },
} as const;
