/**
 * ============================================================================
 * TRIO BUILT GULF — SITE CONTENT
 * ============================================================================
 * Every piece of editable copy, contact detail and list on the website lives
 * in this one file. Change it here and it updates everywhere.
 *
 * NOTE ON ACCURACY: this file deliberately contains no invented certifications,
 * awards, project counts, years of experience or client names. Placeholders
 * that are ready for real data are marked with `TODO`.
 * ============================================================================
 */

export const company = {
  name: "Trio Built Gulf",
  legalName: "Trio Built Gulf Technical Services LLC",
  nameLine1: "TRIO BUILT GULF",
  nameLine2: "TECHNICAL SERVICES LLC",
  tagline: "Engineering Excellence. Built for Performance.",
  city: "Dubai",
  country: "United Arab Emirates",
  location: "Dubai, United Arab Emirates",
  email: "triobuiltgulf@gmail.com",
  /** Primary operations line */
  phone: {
    label: "+971 52 507 3289",
    href: "tel:+971525073289",
    whatsapp: "971525073289",
  },
  /** Co-Founder direct line */
  phoneAlt: {
    label: "+971 55 625 4138",
    href: "tel:+971556254138",
    whatsapp: "971556254138",
  },
  /** TODO: add the trade licence number and full street address when available. */
  address: {
    street: "",
    locality: "Dubai",
    region: "Dubai",
    country: "AE",
  },
} as const;

/**
 * OFFICIAL LOGO ARTWORK
 * ---------------------
 * Master: `public/images/trio_built_gulf_logo_high_resolution.png` — the
 * supplied high-resolution original. Its colours are the authoritative brand
 * values (navy #0A2E50 / #102A4B, teal #348171) and are never altered.
 *
 * The derived files are generated by `scripts/build-logo.mjs`, which lifts the
 * master's light grey ground to transparency and writes a white-navy colourway
 * for the site's navy sections. Their paths live in `logo-assets.ts`, which
 * that script generates — the filenames are content-hashed, so replacing the
 * master and rebuilding pushes the new logo out past every browser cache.
 *
 * To update the logo: replace the master, then run
 *     node scripts/build-logo.mjs
 */
export { logoAssets } from "./logo-assets";

export const whatsappLink = (phone: string, message: string) =>
  "https://wa.me/" + phone + "?text=" + encodeURIComponent(message);

export const defaultWhatsAppMessage =
  "Hello Trio Built Gulf, I would like to enquire about your technical services.";

/* -------------------------------------------------------------------------- */
/*  NAVIGATION                                                                */
/* -------------------------------------------------------------------------- */

export const navLinks = [
  { label: "Home", href: "/#home" },
  { label: "About", href: "/#about" },
  { label: "Services", href: "/#services" },
  { label: "Projects", href: "/#projects" },
  { label: "Why Us", href: "/#why-us" },
  { label: "Team", href: "/#team" },
  { label: "Contact", href: "/contact" },
] as const;

/* -------------------------------------------------------------------------- */
/*  STATS — factual only, no invented numbers                                 */
/* -------------------------------------------------------------------------- */

export type Stat = {
  value: number | null;
  display?: string;
  suffix?: string;
  label: string;
};

export const stats: Stat[] = [
  { value: 11, suffix: "+", label: "Core Services" },
  { value: null, display: "UAE", label: "Based Operations" },
  { value: 24, suffix: "/7", label: "Service Support" },
  { value: 100, suffix: "%", label: "Client Focus" },
];

/* -------------------------------------------------------------------------- */
/*  CORE SERVICES                                                             */
/* -------------------------------------------------------------------------- */

export type Service = {
  slug: string;
  title: string;
  description: string;
  icon: string;
  /**
   * Card photograph.
   * TODO: replace each of these with a real photograph of the trade — they
   * currently reuse the site's general imagery as stand-ins.
   */
  image: string;
  alt: string;
};

export const services: Service[] = [
  {
    slug: "false-ceiling-partitions",
    title: "False Ceiling & Light Partitions Installation",
    description:
      "Suspended ceiling systems and lightweight partitioning installed to line, level and specification.",
    icon: "LayoutPanelTop",
    image: "/images/feat-interior.jpg",
    alt: "Suspended ceiling and light partition installation",
  },
  {
    slug: "hvac-ventilation",
    title: "Air-Conditioning, Ventilation & Air Filtration",
    description:
      "Cooling, ventilation and filtration works that keep indoor environments comfortable and clean.",
    icon: "Wind",
    image: "/images/feat-mep.jpg",
    alt: "Air-conditioning and ventilation plant",
  },
  {
    slug: "systems-installation",
    title: "Systems Installation & Maintenance",
    description:
      "Building systems installed, commissioned and maintained for dependable day-to-day operation.",
    icon: "Settings2",
    image: "/images/proj-facilities.jpg",
    alt: "Building systems installation on site",
  },
  {
    slug: "painting",
    title: "Painting Contract",
    description:
      "Surface preparation and application delivering an even, durable and consistent finish.",
    icon: "Paintbrush",
    image: "/images/proj-residential.jpg",
    alt: "Painting and surface finishing works",
  },
  {
    slug: "steel-products",
    title: "Steel Products Installation & Maintenance",
    description:
      "Fabricated steel elements installed, fixed and maintained with structural care.",
    icon: "Hammer",
    image: "/images/proj-commercial.jpg",
    alt: "Structural steel elements in place",
  },
  {
    slug: "glass-aluminum",
    title: "Glass & Aluminum Installation & Maintenance",
    description:
      "Glazing, aluminum framing and facade elements fitted for alignment, sealing and finish.",
    icon: "Frame",
    image: "/images/about-towers.jpg",
    alt: "Glazed aluminium facade",
  },
  {
    slug: "tiling",
    title: "Floor & Wall Tiling Works",
    description:
      "Precise setting-out and laying of floor and wall tiles across wet and dry areas.",
    icon: "Grid3x3",
    image: "/images/proj-interior.jpg",
    alt: "Floor and wall tiling works",
  },
  {
    slug: "plumbing-sanitary",
    title: "Plumbing & Sanitary Installations",
    description:
      "Supply, drainage and sanitary fittings installed and tested for leak-free performance.",
    icon: "Droplets",
    image: "/images/feat-maintenance.jpg",
    alt: "Plumbing and sanitary pipework",
  },
  {
    slug: "carpentry-flooring",
    title: "Carpentry & Wood Flooring Works",
    description:
      "Joinery, fit-out carpentry and wood flooring executed with a clean, considered finish.",
    icon: "Ruler",
    image: "/images/proj-maintenance.jpg",
    alt: "Carpentry and wood flooring works",
  },
  {
    slug: "electrical",
    title: "Electrical Fittings & Fixtures Repairing & Maintenance",
    description:
      "Fittings, fixtures and circuits installed, repaired and maintained to operate safely.",
    icon: "Zap",
    image: "/images/contact-plans.jpg",
    alt: "Electrical fittings and distribution board",
  },
  {
    slug: "plaster",
    title: "Plaster Works",
    description:
      "Internal and external plastering producing flat, true and paint-ready surfaces.",
    icon: "Layers",
    image: "/images/cta-architecture.jpg",
    alt: "Internal plastering works",
  },
];

/* -------------------------------------------------------------------------- */
/*  FEATURED SERVICE CATEGORIES                                               */
/* -------------------------------------------------------------------------- */

export type Featured = {
  index: string;
  title: string;
  summary: string;
  points: string[];
  image: string;
  alt: string;
};

export const featured: Featured[] = [
  {
    index: "01",
    title: "MEP & HVAC",
    summary:
      "Air-conditioning, ventilation, air filtration, plumbing and electrical works — the systems that make a building work.",
    points: [
      "Air-conditioning & ventilation",
      "Plumbing & sanitary",
      "Electrical fittings & fixtures",
    ],
    image: "/images/feat-mep.jpg",
    alt: "Modern commercial office interior with exposed ceiling services and ventilation ductwork",
  },
  {
    index: "02",
    title: "Interior & Finishing",
    summary:
      "False ceilings, partitions, tiling, plaster, carpentry and painting brought to a consistent, considered finish.",
    points: [
      "False ceilings & partitions",
      "Tiling, plaster & painting",
      "Carpentry & wood flooring",
    ],
    image: "/images/feat-interior.jpg",
    alt: "Completed premium interior fit-out with timber detailing and recessed lighting",
  },
  {
    index: "03",
    title: "Maintenance & Installation",
    summary:
      "Steel, glass and aluminum installation alongside ongoing maintenance that protects performance over the long term.",
    points: [
      "Steel products installation",
      "Glass & aluminum works",
      "Planned & reactive maintenance",
    ],
    image: "/images/feat-maintenance.jpg",
    alt: "Technician welding a steel section during an installation and maintenance activity",
  },
];

/* -------------------------------------------------------------------------- */
/*  WHY US                                                                    */
/* -------------------------------------------------------------------------- */

export const differentiators = [
  {
    index: "01",
    title: "Quality First",
    description:
      "Every installation and maintenance activity is approached with attention to workmanship and detail.",
    icon: "BadgeCheck",
  },
  {
    index: "02",
    title: "Reliable Execution",
    description:
      "Professional coordination and dependable service delivery for every requirement.",
    icon: "CalendarCheck",
  },
  {
    index: "03",
    title: "Complete Solutions",
    description:
      "Multiple technical disciplines brought together under one service partner.",
    icon: "Layers3",
  },
  {
    index: "04",
    title: "Client Focused",
    description:
      "Solutions designed around project requirements, operational needs and long-term performance.",
    icon: "Target",
  },
] as const;

/* -------------------------------------------------------------------------- */
/*  PROJECT CAPABILITIES                                                      */
/*                                                                            */
/*  These are CAPABILITY CATEGORIES, not real project records. To publish an  */
/*  actual project, add `client`, `location` and `year` to an entry below and */
/*  the ProjectCard renders that metadata automatically.                      */
/* -------------------------------------------------------------------------- */

export type Project = {
  slug: string;
  category: string;
  title: string;
  description: string;
  image: string;
  alt: string;
  /** TODO: fill in once real, approved project references are available. */
  client?: string;
  location?: string;
  year?: string;
};

export const projects: Project[] = [
  {
    slug: "commercial",
    category: "Commercial",
    title: "Commercial Facilities",
    description:
      "Offices, retail units and commercial premises — technical installation and finishing works coordinated around live operations.",
    image: "/images/proj-commercial.jpg",
    alt: "Contemporary commercial building with a glass and metal panel facade",
  },
  {
    slug: "interior",
    category: "Interior",
    title: "Interior Fit-Out",
    description:
      "Ceilings, partitions, flooring, joinery and finishes delivered as a single coordinated interior package.",
    image: "/images/proj-interior.jpg",
    alt: "Bright interior fit-out with timber staircase, balustrade and pendant lighting",
  },
  {
    slug: "facilities",
    category: "Facilities",
    title: "Building Maintenance",
    description:
      "Planned and reactive maintenance that keeps building services and finishes performing day after day.",
    image: "/images/proj-facilities.jpg",
    alt: "Maintained corridor in a modern facility with a clean suspended ceiling system",
  },
  {
    slug: "mep",
    category: "Maintenance",
    title: "MEP Installation",
    description:
      "Air-conditioning, ventilation, plumbing and electrical installations executed and tested to specification.",
    image: "/images/proj-maintenance.jpg",
    alt: "Detail of a polished sanitary fitting following a plumbing installation",
  },
  {
    slug: "residential",
    category: "Residential",
    title: "Residential & Technical Works",
    description:
      "Villas and residential buildings — technical works, upgrades and finishing carried out with minimal disruption.",
    image: "/images/proj-residential.jpg",
    alt: "Modern residential building exterior illuminated at dusk",
  },
];

/* -------------------------------------------------------------------------- */
/*  PROCESS                                                                   */
/* -------------------------------------------------------------------------- */

export const process = [
  {
    index: "01",
    title: "Understand",
    description: "Understand project requirements and site conditions.",
  },
  {
    index: "02",
    title: "Plan",
    description: "Develop the appropriate technical approach.",
  },
  {
    index: "03",
    title: "Execute",
    description: "Deliver installation or maintenance works professionally.",
  },
  {
    index: "04",
    title: "Inspect",
    description: "Review workmanship and technical completion.",
  },
  {
    index: "05",
    title: "Support",
    description: "Provide ongoing maintenance and service support.",
  },
] as const;

/* -------------------------------------------------------------------------- */
/*  TEAM — taken from the official business cards. No invented biographies.   */
/* -------------------------------------------------------------------------- */

export type TeamMember = {
  name: string;
  role: string;
  initials: string;
  phone?: { label: string; href: string; whatsapp: string };
  email?: string;
  /** Downloadable contact card — the digital equivalent of the printed card QR. */
  vcard?: string;
  /**
   * The official printed business card, rendered from the supplied PDF in
   * `assets/business-cards`.
   */
  card?: string;
  cardAlt?: string;
};

export const team: TeamMember[] = [
  {
    name: "Lakshmikandh Ramadas",
    role: "Co-Founder",
    initials: "LR",
    phone: company.phone,
    email: company.email,
    vcard: "/contacts/lakshmikandh-ramadas.vcf",
    card: "/images/card-lakshmikandh-ramadas.jpg",
    cardAlt:
      "Business card for Lakshmikandh Ramadas, Co-Founder at Trio Built Gulf Technical Services LLC",
  },
  {
    name: "Dilipkumar Muthaiah",
    role: "Co-Founder",
    initials: "DM",
    phone: company.phoneAlt,
    email: company.email,
    vcard: "/contacts/dilipkumar-muthaiah.vcf",
    card: "/images/card-dilipkumar-muthaiah.jpg",
    cardAlt:
      "Business card for Dilipkumar Muthaiah, Co-Founder at Trio Built Gulf Technical Services LLC",
  },
];

/* -------------------------------------------------------------------------- */
/*  TESTIMONIALS                                                              */
/*                                                                            */
/*  Intentionally EMPTY — no testimonials have been invented. Add real,       */
/*  approved client quotes here and the testimonial section appears on the    */
/*  home page automatically; while the array is empty the section is hidden.  */
/* -------------------------------------------------------------------------- */

export type Testimonial = {
  quote: string;
  author: string;
  role: string;
  company: string;
};

export const testimonials: Testimonial[] = [];

/* -------------------------------------------------------------------------- */
/*  ENQUIRY FORM OPTIONS                                                      */
/* -------------------------------------------------------------------------- */

export const serviceOptions: string[] = [
  ...services.map((s) => s.title),
  "General Enquiry",
];
